name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Azure DevOps remote
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://anyuser:$AZURE_DEVOPS_PAT@dev.azure.com/andersgravesen/Food/_git/food-data-api

      - name: Fetch and rebase from Azure DevOps
        run: |
          git fetch azure main
          git rebase azure/main

      - name: Push to Azure DevOps
        run: |
          git push azure main --force-with-lease
